### ISSUE TITLE
[RM] VNF Evolution Policy

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#1007]
The following 5 constituent issues (plus a potential 6th issue) have been identified as comprising the challenge of implementing VNF Evolution, specifically through "VNF Profile Generations" (refer to RM deep-dive presentation from Prague).
For additional information, refer to:
- Issue #750  // discussion of the VNF Evolution Framework requirements
- [Prague RM deep-dive presentation](https://wiki.lfnetworking.org/download/attachments/27525468/CNTT_RM_Core_DeepDive_20200116.pdf?version=3&modificationDate=1579166810000&api=v2) // Slide 9 to 11
- [RM Core Team meeting minutes of 29/1/2020](https://wiki.lfnetworking.org/display/LN/2020-01-29+-+%5BCNTT+-+RM+Workstream+Master%5D+Agenda+and+Meeting+Minutes)

1. In an OpenStack environment, what is the best way to schedule workloads against the correct variant (i.e. revision) of a flavor when using the Compute API? In other words, if there are multiple variants for a given flavor, such as version 1, ver 2, ver 3, etc., what is the best way to utilize the Compute API to instantiate the correct variant for a workload. Two examples are provided, but we are open to other options:
- Create a new flavor every time a new version of a profile is needed, then overload the flavor’s name w/ the variant. For example, Basic_v1, Basic_v2, etc. API calls would populate flavorRef = Basic_v2, etc.
- Have a single, static, base flavor name (e.g., Basic), and use a scheduler_hint parameter to identify the variant.  In this scenario, API calls would populate flavorRef = Basic, and populate os:scheduler_hints = v2
- Other ideas?

Note, the intent behind the variant is to be able to target workloads at compute resources that are compatible w/ with the requirements of the workloads.
 
 
2. Should profile variant identifiers, which are simply integers, potentially w/ a “v” prefix (e.g., v1, v2, v3, etc.), be kept in lock step w/ CNTT release numbers? For example, profile variants in CNTT Rls n, would all be variant n. When a new CNTT release is produced, all profile variants will increment to stay aligned w/ the overall rls number. This includes releases where there are no changes to the variants – when the CNTT rls number changes, so does the profile variant identifier associated with that release.
- What are the drawbacks to this methodology?
- What happens if a new CNTT rls comes out and there are no changes to the profile? Do we increment the variant anyway, just to keep it in sync w/ the CNTT rls?
- **CONCLUSION:** We will synchronize the variant numbers w/ the CNTT release number for the time being. We can revisit this policy n the future, if needed.  
 
3. How are Infra upgrades to be implemented and supported? We propose a make-before-break approach, where upgraded nodes are added to the Infra when convenient, and workloads are cutover to the new Infra once they’re certified or replaced with VNFs that are certified for the new profile variant
4. What is forward compatibility directive (policy/strategy) for CNTT? // for TSC/Gov
5. What is backwards compatibility directive (policy/strategy) for CNTT? // for TSC/Gov

**Comment by pgoyal01** [comment]
@rabi-abdel there are no versions in OSTK. You are basically creating new flavors and these flavors are then specified during the instance create call (openstack server create --flavor <flavorid> ...).

**Comment by kedmison** [comment]
Conceptually, it would appear that defining the forwards/backwards compatibility policy first would provide guidance on the remaining issues 1, 2, 3. 

Accordingly, issues #1008  and #1009 have been created to discuss the forward/backwards compatibility issues, and to identify how the RM should reflect these policies.  Then, we can approach issues 1/2/3.

**Comment by pgoyal01** [comment]
In the main write-up some terms are being used interchangeably-- for example, flavors and profiles.  The following is a long write-up - my sincerest apologies; the Background information can be skipped by those knowledgeable about OpenStack. Many details have been simplified for convenience.

Before we can define a policy we need to get on the same page w.r.t. the terms and the life cycle of certain things. 

**Background**

Typically, a data center would consist of compute hosts of different types (manufacturer, size (e.g., cores, speed, etc.). Over time, new compute hosts will be introduced either during hardware refresh cycles or during  augments (extra capacity adds). 

Compute flavors specify not only the virtual resource geometry (sizing such vCPU=2, RAM=8GB, etc.) but also extra specifications such as CPU Topology (for a VM the number of cores, sockets, threads, ..), CPU Pinning policy, NUMA topology,  PCI Passthrough, etc. These extra specs or metadata can be set during initial flavor create or set later on.

In OpenStack (simplified view), when an instance (create server) of a certain flavor type is to be created, a target compute host is selected for the creation of the instance (VM) from a host aggregate that matches the flavor metadata. The create server takes flavor as a parameter (can also specify the VM geometry rather than the flavor) and also specify the metadata.

Compute hosts are configured as per software and hardware profiles (RM uses the term NFVI profile). They are associated with host aggregates with metadata that captures at least some of the compute host configurations. For example, a host aggregate of SR-IOV capable compute hosts.

**Flavors, Flavor Series and Instance Types**
- The flavor series (.tiny, .medium, ...) is specified in terms of geometry
- A flavor is created (with the flavor series name) and the VM Geometry 
- The flavor may be created with the capabilities of the Instance Type specified as flavor metadata
- The flavor may also be created with disk I/O, bandwidth I/O and other capabilities also specified as metadata
- Instead of the various capabilities specified as metadata for a flavor, they can be specified as metadata during instance (VM) create 
    - if not specified in the flavor but specified as metadata during instance create, allows for flavors that do not have to change with changes to underlying hardware
- The metadata may also specify technologies that are subject to exception policies (such as SR-IOV)

We may therefore define flavors as in the following examples:

| Instance Type | Flavor Series | CPU Allocation |SMT | CPU Pinning | NUMA | Huge Pages | SR-IOV (s) | DPDK (d) | Kernel vRouter (v) |
|--------------|-------|------|--------------|--------|--------|-------------|---------|-------|------|
| B | .medium | 1.0 |Yes | No | No | No | No | No | Yes |
| B | .medium | 4.0 |Yes | No | No | No | No | No | Yes |
| NI | .large | 1.0 |Yes | Yes | Yes | Yes  | Yes | No | Yes |
| NI | .large | 1.0 |Yes | Yes | Yes | Yes | No | Yes | Yes | 

- we need a flavor naming convention that allows us to differentiate between variants, for example, the 2 Basic .medium flavors and the 2 NI .large flavors.
- example naming convention: <Instance Type><networking (d,s,v)><cpu allocation ratio><flavor series>. 

| Flavor | Instance Type | Flavor Series | CPU Allocation |SMT | CPU Pinning | NUMA | Huge Pages | SR-IOV (s) | DPDK (d) | Kernel vRouter (v) |
|--- |--------------|-------|------|--------------|--------|--------|-------------|---------|-------|------|
| Bv1.0.medium | B | .medium | 1.0 |Yes | No | No | No | No | No | Yes |
| Bv4.0.medium | B | .medium | 4.0 |Yes | No | No | No | No | No | Yes |
| NId1.0.large | NI | .large | 1.0 |Yes | Yes | Yes | Yes  | Yes | No | Yes |
| NIs1.0.large | NI | .large | 1.0 |Yes | Yes | Yes | Yes | No | Yes | Yes | 

> Please note that in OpenStack the default CPU Allocation Ratio is 16.0 and thus it is important to set the ratio value if do not want the default setting.

**LCM**

*Addition of new compute hosts*

Let us assume that a set of compute hosts are configured as per NFVI profiles C<sup>o</sup> (for simplicity will refer to C<sup>o</sup> as a type), and that these compute hosts are configured for a technology that falls under an exception.  A new set of compute hosts are introduced of type C' that eliminate the need for the exception. The introduction of these new compute hosts have certain capabilities that are different from existing computing hosts. To make these new capabilities available to VNFCs, new C' NFVI profiles and host aggregates would need to be created.  New flavors may also need to be created if the flavors incorporate certain metadata.

*VNF Evolution 1*

VNF developers desiring to use the new capabilities will develop a new version of the VNF (typically some of the component VNFCs that depended upon the exception) that utilises the new flavors. Let us label the older version VNF as V<sup>o</sup> and the newer version VNF as V'. 

While both the compute hosts of type C<sup>o</sup> and C' exist, both VNF<sup>o</sup>and VNF' must be supported; this in turn requires the support of the corresponding flavors and NFVI profiles.

*VNF Evolution 2*

In this use case, the VNF developer wants to utilise features available in the newer CNTT OpenStack release. During the upgrade of OpenStack across all regions of the enterprise cloud (not all regions will be updated simultaneously), both VNF versions would need to exist.

*Flavor Evolution*

New flavors may need to be created if the metadata is specified as part of the flavor. If the metadata is not assigned for a flavor, then we may not need to create a new flavor when, say, new compute hosts are introduced.

If however metadata is part of flavors then as discussed above new flavors will have to be created and the older flavor type will need to exist as long as there are VNFs (VNFCs) that utilise those flavors.

**Comment by karinesevilla** [comment]
To be deployed, VNFs or CNFS need a NFVI instance type (defined by a NFVI HW + SW profile) and a compute flavor (definitions in RM Glossary).
In my opinion, the Reference Model should focus on the description of NFVI instance type. The detailed description of flavors should be part RA, it's difficult to have a description applicable both for VMs and containers. @pgoyal01, I like the way Pankaj described the flavors, but I think it should be part of RA1 rather than RM.
The NFVI instance types will evolve over time and availability of new technologies, new profiles will be created and other profiles as described in transitional plan will be removed of CNTT reference. 
We can name the different NFVI instance types per family and capabilities, for instance NI_DPDK, NI_SRIOV, NI_SmartNic and link these instances types to a CNTT release.

**Comment by pgoyal01** [comment]
@karinesevilla my intent was not to introduce flavors as part of the RM. As I stated at the beginning, my objective of writing the comment was to get all of us on the same page as far as the terms are concerned and their relationships.

**Comment by rabi-abdel** [comment]
@kedmison feel free to re-assign to Technical Steering whenever a decision is needed to be made that you would like the Technical Steering to take. for now, it is kept for RM WS to handle it.

**Comment by CsatariGergely** [comment]
#1493 solves this on RM level with a proposal on the flavor names. 
@rabi-abdel , @pgoyal01 please check the proposal from RA1 point of view
@rabi-abdel , @tomkivlin however flavors can not be interpreted on a Kubernetes environment, but maximum sizes of Pods and used capabilities can be. We should check the proposal and think about how to implement it to RA2.

**Comment by rabi-abdel** [comment]
> #1493 solves this on RM level with a proposal on the flavor names.
> @rabi-abdel , @pgoyal01 please check the proposal from RA1 point of view
> @rabi-abdel , @tomkivlin however flavors can not be interpreted on a Kubernetes environment, but maximum sizes of Pods and used capabilities can be. We should check the proposal and think about how to implement it to RA2.

@CsatariGergely Yes, sounds good.

**Comment by pgoyal01** [comment]
@CsatariGergely Flavor naming is flexible in  OSTK and so this proposal is OK

**Comment by kedmison** [comment]
Can we agree that this issue can be closed when the PRs for #1008 and #1009 are closed?
