### ISSUE TITLE
[TSC] Edge Reference Architecture-New work-stream

### ISSUE THREAD

**Issue by ASawwaf** [cntt-n/CNTT#1031]
To be discussed in TSC

https://etherpad.opnfv.org/p/Edge

Decision will be:

- New stream?
  - new RA? or within existing RAs

**Comment by rabi-abdel** [comment]
to be discussed in next week.

**Comment by petorre** [comment]
Current RAs are based on technologies designed for large enough cluster sizes per Edge site, but not for On-premise single server like example case handled differently. I'm happy to join team writing that.

**Comment by trevgc** [comment]
The Edge discussion etherpad link above (https://etherpad.opnfv.org/p/Edge) just takes me to https://etherpad.opnfv.org/p/RI2. Does it work for others?

**Comment by rabi-abdel** [comment]
> The Edge discussion etherpad link above (https://etherpad.opnfv.org/p/Edge) just takes me to https://etherpad.opnfv.org/p/RI2. Does it work for others?

@trevgc I think what happened was the text from RI2 was copied in there. I have cleaned it up. it should be clear now. it will be good to start collecting thoughts. @ASawwaf may be you can draft something for people to start with? or possibly we can wait until your presentation next week.

**Comment by ASawwaf** [comment]
@trevgc @ASawwaf , I am done with draft content, I encourage all to participate

**Comment by tomkivlin** [comment]
My preference would be that edge non-functional requirements are included in the existing RAs and the original intent of an RA being technology specific is retained. If a new edge-specific technology (e.g. EdgeX  Foundry) is needed then I think it's a new RA.

**Comment by TFredberg** [comment]
I would second @tomkivlin in that RA ought to enable different deployment implementations and if it doesn´t support Edge sized deployments today, the first choice should be to extend respective RA.
I also think that most VNFs and CNFs should be and would like to be unaware of if they are deployed in a central, regional, edge or even far edge environment.
If we start differentiating the VNFs and CNFs depending on their deployments the design and testing effort will increase a lot.

**Comment by hdamker** [comment]
I also second to the two previous comments of @tomkivlin and @TFredberg. The intention of CNTT is mainly to define the interface between NFVI and VNFs respective CNFs. NFVI has to be seamless across the telco infrastructure from central DC to the edge from VNF perspective and orchestration (north-bound interfaces). 

If the current version of RA 1 or RA 2 does not allow to scale an implementation down for the edge cases (or even work with a remote infrastructure control plane) we should reconsider the requirements which are imposing that in the RM or RA -- they are maybe not following the initial principles of CNTT.

What might be necessary for use case like vRAN could be the introduction of an additional profile (e.g. including hardware acceleration with FGPA or GPU for radio processing), if the current modularity does not allow for that anyway. But here my proposal would be to leave this first to more specific projects like O-RAN WG 6. 

On CNTT side we maybe should just make sure that the Reference Model and technology specific Reference Architecture can be used in project like O-RAN WG 6 as base and guidance, and later integrate the results from these projects back into CNTT, in perfect case by just referencing them as compliant reference implementations, in other cases by integrating additional requirements after they are sorted out in the more specific projects.

Happy to contribute if we decide that Edge WG in CNTT will just review the existing specifications and change them where necessary so that they can fit also for Edge cases.

**Comment by karinesevilla** [comment]
I prefer to keep the Edge topic within RA1 and RA2 at the moment. Additional profiles (mostly HW specific profiles) will probably be necessary for that, but This can be done according to use cases requirements when these requirements are clearly raised. Relying on existing projects like O-RAN is a good approach to catch Telco relevant use cases.

**Comment by bfcohen** [comment]
I have VERY mixed feelings on this.  Edge as many of you know, is still an emerging technology, with no single clear set of use cases or definitions even of what constitutes "Edge".   There are a number of metrics, or as I think of them, levers, that drive the Edge Use Cases and Architectures. WAN distance or latency concerns, significant hardware constraints, limited tools for distributed management (and a disagreement on how much management needs to be remote rather than centralized) and the need for optimizing distributed applications. Edge can be deployed in a fully meshed architecture or in a hierarchical architecture with or without a cloud core.  
Within the Telecom industry, Edge is frequently associated with 5G and MEC, and the need for more distributed access points, but if you dig into that use case, many of the access points are really mini-data centers, not what the word Edge would normally evoke for the average person.  That being said, the telecom industry is in fact in the best position to support Edge architectures, because in ALL the definitions of Edge, there is one consistency -- the WAN network is a major component.
So where does this leave CNTT on the question?  Yes we do need to have some stance on Edge, certainly as an industry , vendors and operators alike, as working on building out Edge infrastructure.  However, Edge is typically some combination of Cloud Hypervisor supported VMs and containers.  Obviously, containerized architectures is the preferred architecture, but as I found out in building an Edge product over the past few years, the world is not quite ready for a fully containerized infrastructure, so we have had to make due with what is available and fill in the gaps.  Possibly we should start by digging into the Telecom use cases that already exist to see where they fit, before committing to starting a third workstream.  At this point I am leaning on the side of adding chapters and flavors in the RA1 and RA2 sections, but I am open to other ways of doing it -- as long as we don't go down the path of reinventing the great amount of work that has already been done in other groups.

**Comment by rabi-abdel** [comment]
slides shown by @bfcohen @ASawwaf @ildilo https://wiki.lfnetworking.org/download/attachments/33424163/Edge_CNTT%20V1.pptx?api=v2

**Comment by hdamker** [comment]
Where or how can we discuss the content of the slides? 

Some points/questions:

- Slide 4: is my understanding correct that the intended scope of the focus group should be on the left box only ("Infrastructure")?
- Slide 5: The technical work/framework for GSMA TEC will be done in GSMA OPG (Operator Platform Group), targeting a PRD (Permanent Reference Document). So GSMA OPG would be more correct here.
- Slide 10: same here
- Slide 13: The large red CNTT block could be understood that CNTT address everything from Device to Telco Edge Cloud. Shouldn't be the focus of CNTT on Telco Edge Cloud only?

**Comment by ASawwaf** [comment]
@hdamker , thanks herbert, i will address you comments

**Comment by ASawwaf** [comment]
Hello @hdamker 

Slide 4: is my understanding correct that the intended scope of the focus group should be on the left box only ("Infrastructure")?

@ASawwaf : Yes, as the complete scope of CNTT covers the infrastructure, therefor edge will follow CNTT Sccpe covers the infrastructure.

Slide 5: The technical work/framework for GSMA TEC will be done in GSMA OPG (Operator Platform Group), targeting a PRD (Permanent Reference Document). So GSMA OPG would be more correct here.

@ASawwaf : Sure, corrected 

Slide 10: same here

@ASawwaf:  Sure, corrected 


Slide 13: The large red CNTT block could be understood that CNTT addresses everything from Device to Telco Edge Cloud. Shouldn't be the focus of CNTT on Telco Edge Cloud only

@ASawwaf : Thanks, Corrected 

I will share the updated slides
