### ISSUE TITLE
[RA2] Ch4 - Clarify requirement on conformant K8s installer for RI

### ISSUE THREAD

**Issue by gkunz** [cntt-n/CNTT#1038]
Chapter 6 of RA2 currently states:
"The Kubernetes distribution or product that is used in the RI must be listed in the Kubernetes Distributions and Platforms document and marked (X) as conformant for the Kubernetes version that is being used."

https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter04.md#43-kubernetes

For the purpose of RI2, we should be a bit more precise here and stating that the RI should make use of an installer which is conformant. Otherwise we would not be able to consider tools like metal3 or the CNF testbed as candidates for RI2 because they are not listed. However, these higher layer installers make use of kubeadm or kubespray under the hood which are listed.

Moreover, I'd like to include the term "[installer] project" in addition to "k8s distribution or product"

**Comment by tomkivlin** [comment]
Hi @gkunz I'm not sure I see the need for a change.  CNF testbed isn't a tool or an installer, and as you say the installer it uses is kubespray so that would be compliant.  And if metal3 isn't conformant with the CNCF tests then I would argue we shouldn't use it.  

Happy to improve the wording to include installer in that section though, that makes sense.
