### ISSUE TITLE
[RM] Workloads in transitional period need a larger flavour size

### ISSUE THREAD

**Issue by kedmison** [cntt-n/CNTT#1057]
This issue is to request the addition of one larger size in the pre-defined compute flavours: a 32-core, 64GB RAM variant.  

**Rationale**
There are cases today where horizontally-scaled workloads are using multiple large VMs (32-core, 64-GB RAM VMs).  These workloads are deployed today in NFVIs.  These workloads are horizontally scaled already, and yet still require the large per-VM instance memory profile.

**Comment by pgoyal01** [comment]
@kedmison This cannot be a flavour required by operators to support by default; operators may have processes to allow for such a large flavour.  If an operator needs to support such a large flavour they can create one when required after following required processes.

**Comment by petorre** [comment]
If agreed to be common and undesired, maybe this is for Exception Policy, which still helps going towards desired defragmentation.

**Comment by ASawwaf** [comment]
@pgoyal01 @kedmison  , Yup, it is not large, it is huge flavour :) ,  i don't believe there is any VNF required such amount of core 
and on Intel x86 Cascadelake the max core per socket is 28 Core , ( Intel has 32-56 Core / not for NFV ) So either to adapt this number of Core /server or lets this very fat VNF to cross NUMA  @petorre to comment

**Comment by petorre** [comment]
> lets this very fat VNF to cross NUMA

Since introduction of NUMA (10+ years before Intel implementations) there were SW optimizations needed to take advantage of local vs remote memory.
Most VNFs get placed with all vCPUs on same NUMA node, getting traffic over PCI busses connected, talking Huge Pages to local memory. With that target should this Profile be written.
Getting VNF to work over to another NUMA node (both on another socket or inside same multi-die package) would require both VNF design+support and correct placement, which generally is not being done. Here I would ask for further comments from representative of VNF vendors with products in rare categories that are not being decomposed into smaller components.

**Comment by kedmison** [comment]
It's not that large; 32 vCPUs is 32 threads at the host level.  Over 60% of the current Cascade Lake lineup has 16 or more cores, and would thus support this size in a single NUMA zone.

**Comment by CsatariGergely** [comment]
Yes, @ASawwaf please do not forget hyperthreading. With this considersed I woluld really consider 32 vCPU-s only big, but not huge.

**Comment by ASawwaf** [comment]
Great , so @kedmison , in the issue description, you mention 32-Core which means 64 vCPU , in this case, it is huge 

but if it 32 vCPU , for sure it will be fit ;)
