### ISSUE TITLE
[RA1 Ch05] Review the lists of OpenStack services mandatory features 

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#1156]
Check features available for Pike release

**Comment by msidana** [comment]
I'd be happy to work on this.

**Comment by pgoyal01** [comment]
@msidana Thanks -- assigned to you.

**Comment by pgoyal01** [comment]
@msidana What is the status of this? Please update. Thanks

**Comment by pgoyal01** [comment]
Moved to Backlog as requires extensive review in coordination with RC-1

**Comment by collivier** [comment]
@karinesevilla @pgoyal01 
The following requirements are false because the service is a must requirement and the capabilities exposed is a should one (False from a Chapter 5 statepoint)
- req.inf.stg.06
- req.inf.stg.11
- req.inf.ntw.18

The mandatory services (core services as proposed could be improved) are not only about Cinder, Glance and Neutron. If we decouple the API and the capabilities, we must list the remaining services. It should be noted that links to Chapter 5 would be better than a link to OpenStack

Merging API, capabilities, version and the status expected in one requirement could have rather made sens.

They are "should" requirements uncovered by an API (SFC, Telemetry, Cyborg). They are defacto out of Functest scope and must be removed from traceability matrix (it's an issue between RM and RA1)

**Comment by karinesevilla** [comment]
@collivier @pgoyal01 
Proposal to address Cédric comment with PR #1622 which detail the mandatory services in API section.
As it is impossible to describe all the mandatory features in chapter 2, a reference is made for each mandatory service to chapter 5

**Comment by pgoyal01** [comment]
Worked in two PRs already. will close and if needed we will open issues.
