### ISSUE TITLE
[R2 Ch4] likely belongs in RI2

### ISSUE THREAD

**Issue by fkautz** [cntt-n/CNTT#1186]
A significant portion of this document appears to belong in the RI2, not RA2. It details implementation details into the RA. It also is written in a way that blocks the use of hosted cloud environments such as GKE, EKS and AKS. 

In short, we should migrate these into the RI.

Here is a quick list of things that appear to the implementation details:

* OS package managers (not to the benefit of K8s)
* K8s installer
* Specific K8s versions
* Specific container runtimes
* Specific CNI multiplexer/metaplugins (danm/multus)
* Pegs Calico as the K8s default CNI. The largest used CNI plugins are hosted K8s (GKE/EKS/AKS), not Calico.
* User Space Networking Hosts (VPP, OVS. Where does this leave solutions such as TF vRouter which has heavy use in groups like AT&T?)
* Denies the use of L4/L7 service mesh.
* Pegs Helm v3 (which I think is a good idea, but likely belongs in RI2)

**Comment by gkunz** [comment]
Hi @fkautz.  Good points and and some sections should be moved over to the RI. Yet, many of the statements in the RA document are not stated in a strictly limiting manner, but rather explicitly as "may" requirements or examples, see container runtimes, CNI plugins, helm 3. The RI has to pick one particular component (e.g. Multus or DANM).

To the other points: 
- OS package managers (not to the benefit of K8s)
  -> agreed

- K8s installer
  -> Needs to be rephrased and can be _copied_ to RI. However, this is a generic requirement not mandating a particular installer, but it basically requires that any implementation that intends to be *conformant* to RA2 must pass the K8s conformance tests. GKE, EKS and AKS are passing here.

- Specific K8s versions
  -> does this not have relevance in terms of what capabilities a conformant K8s has, i.e., what APIs and their maturity we can expect from a conformant K8s?

- Denies the use of L4/L7 service mesh.
  -> service meshes can be deployed on top of a conformant K8s. This requirement does actually benefit GKE, EKS and AKS

**Comment by rabiabdel** [comment]
@fkautz please assign a project to the issue otherwise it will likely get lost.

**Comment by fkautz** [comment]
> Hi @fkautz. Good points and and some sections should be moved over to the RI. Yet, many of the statements in the RA document are not stated in a strictly limiting manner, but rather explicitly as "may" requirements or examples, see container runtimes, CNI plugins, helm 3. The RI has to pick one particular component (e.g. Multus or DANM).

"The used CNI multiplexer/metapulgin may be DANM as it provides the possibility to use several other CNI plugins (req.inf.ntw.16) and provides an API based solution to administer the networks (req.inf.ntw.10) from a central point (req.inf.ntw.11)."

This could be a problem with interpretation. May could be "possibly" or "permission." If we've restricted the definition of 'may' to 'possibly' without excluding other solutions then we should be ok.

> 
> To the other points:
> 
> * OS package managers (not to the benefit of K8s)
>   -> agreed
> * K8s installer
>   -> Needs to be rephrased and can be _copied_ to RI. However, this is a generic requirement not mandating a particular installer, but it basically requires that any implementation that intends to be _conformant_ to RA2 must pass the K8s conformance tests. GKE, EKS and AKS are passing here.

I agree and believe this is the intention. Rewording this would be great.

> * Specific K8s versions
>   -> does this not have relevance in terms of what capabilities a conformant K8s has, i.e., what APIs and their maturity we can expect from a conformant K8s?
We're better off listing a minimum set of K8s API versions rather than a specific K8s API. You can install a specific K8s version and still not have the required APIs for a successful deployment.

> * Denies the use of L4/L7 service mesh.
>   -> service meshes can be deployed on top of a conformant K8s. This requirement does actually benefit GKE, EKS and AKS

In practice, I agree. This is primarily about the wording. I believe the intention is to allow this to be installed without requiring it per `req.inf.ntw.15`. Perhaps instead of 'No service meshes are part of the architecture.' we can word it something like 'An SMI compatible service mesh may be installed.' without a specific implementation required.

**Comment by gkunz** [comment]
hi @fkautz ok, I see your point regarding interpretation of "may". My understanding has always been that "may" refers to "possibly", but if that can be expressed more clearly, I am all for it. Moreover, there is a definition of "may" in the beginning of chapter 2, stating: "may: Requirements that are marked as may are considered optional. The same applies to may not." I have the impression this definition does not help here.

Regarding service meshes in the architecture: I kind of agree with your proposal. I think the intention here was to state that the RA2 architecture as such does not include a service mesh, however a RA2 conformant platform should be able to run a service on top, and then allow to utilize SMI when a service mesh is installed (req.inf.ntw.15).

Ok, so overall, some rephrasing is needed.

**Comment by fkautz** [comment]
@gkunz agreed. One thing I'm not clear about is whether the definition only applies to numbered requirements. E.g. one could write "The implementation may deploy a service mesh" vs using it in prose such as "The operator may run linkerd" where the intention is less clear. This will be further complicated by the fact that most people reading this will probably not read the initial definition of 'may' so we just need to be careful with our wording.

**Comment by tomkivlin** [comment]
@fkautz @gkunz I've marked this as backlog for now as it's about ch4, however I think it's a really important discussion.
I've been thinking for a while now whether RA2 Ch4 should, rather than just specifying capabilities and specifications, should start by specifying the success criteria for the tests that will be developed in RC2, once launched.  Ian Well's email from a few weeks back put me on this path.

My thought process is:
Ch2 defines the RA requirements - i.e. the detailed scope of what the RA needs to support and define.
Ch3 defines the high level architecture - i.e. the architecture capabilities
Ch5 defines the interfaces between those capabilities
Ch4, instead of just going into more detail about the capabilities (and interfaces?), could instead describe the results we want (desired outcomes) which are essentially the specifications.  RI2 is then an exercise in designing a solution that we think we deliver those outcomes and RC2 is the activity that defines how we test the RI2 against those outcomes.
(and perhaps we need to swap ch4/5 around, or change the structure so interfaces description falls into ch3 along with capabilities, and ch4 simply deals with the desired outcomes for it all)

The area of RC2 that collates the test cases can then start from the content in chapter 4 of RA2 and take it from there, instead of having to convert wordy/vague architecture specs into test cases.

e.g. 
instead of
> Calico may be used as the CNI what complies with the basic networking assumptions of Kubernetes based on the requirement req.inf.ntw.02 due to it's capability to handle NetworkPolicies, what is missing from Flannel.

we could have something like (completely an example - can be better):
> | Test case / RA Spec # | sub-category | Description | Requirement # |
| -- | -- | -- | -- |
| cert.test.inf.01 / arch.spec.inf.01 | Network Policies | Deploy two Pods and a Network Policy that allows communication between the two and ensure the Pods can communicate with each other. | req.inf.ntw.02 |
| cert.test.inf.02 / arch.spec.inf.02 | Network Policies | Deploy two Pods and a Network Policy that does not allow communication between the two and ensure the Pods cannot communicate with each other. | req.inf.ntw.02 |

What do you think?

**Comment by CsatariGergely** [comment]
I think RA2 should define everything what is visible for the VNF-s, including their descriptors and RI should make choices about things wich are not visible for the VNF-s. 

* OS package managers (not to the benefit of K8s) -> Not visible for the VNF, can be an RI2 decision
* K8s installer -> Not visible for the VNF, can be an RI2 decision
* Specific K8s versions -> Defines the feature set available for the VNF, it should be defined in RA2 
* Specific container runtimes -> Here my knowledge is not good enough do formulate an opinion, but if there are differences between the features of container runtimes (NUMA awareness, Huge Pages, CPU pining, SR-IOV these kind of things) then we need to define at least the set of runtimes in RA2
* Specific CNI multiplexer/metaplugins (danm/multus) -> This is visible to the VNF descriptor, so we should define it (I've softened the musts to may due to some comments received to the pr about the RA should not define things so hard, later in Prague we agreed that yes it should, I just never had the time to change the mays to musts (and let's see what is the result of this discussion))
* Pegs Calico as the K8s default CNI. The largest used CNI plugins are hosted K8s (GKE/EKS/AKS), not Calico. -> This is again visible to the pod manifest, so we should agree on something. we should decide if compatibility with GKE/EKS/AKS or network policies are more important. Okay, maybe we can have two options here, but the whole point of CNTT is to limit options. 
* User Space Networking Hosts (VPP, OVS. Where does this leave solutions such as TF vRouter which has heavy use in groups like AT&T?) -> This is also visible for the VNF, so we have to make choices here. 
* Denies the use of L4/L7 service mesh. -> We can not mandate the usage of this to the VNF-s, but an infra can provide these. This is the consensus we have at the moment. 
* Pegs Helm v3 (which I think is a good idea, but likely belongs in RI2) -> This is again visible for the VNF-s in their Helm charts.

@tomkivlin doing the specification as test cases would be really cool, but also a bit too implicit. Like arch.spec.inf.02 already mentions network policies, so one should know which CNI-s support this and which one do not. And we should define test cases until there is only one the CNI are in game what we selected.

**Comment by tomkivlin** [comment]
> @tomkivlin doing the specification as test cases would be really cool, but also a bit too implicit. Like arch.spec.inf.02 already mentions network policies, so one should know which CNI-s support this and which one do not. And we should define test cases until there is only one the CNI are in game what we selected.

I'm torn - for something like the CNI/network solution, there are a combination of requirements that will define what that needs to be. Network policies, segregation, L2/L3/L4/L7 requirements, ingress, load balancing etc. and so whilst any of Calico, Weave, Cillium, etc. could be used for network policies, the other requirements might start to constrain the choice automatically.

Which is starting to make me think the RI is the better place to define those component choices, but we could add them in the RA in addition to the test case/arch specs as per my suggestion perhaps?  That way we have the test that needs to be passed, plus some guidance for network vendors on what the implementations will be based upon?  It might help with the reasoning behind the choices too?

**Comment by petorre** [comment]
Like during discussions in Prague F2F, I fully agree with @CsatariGergely comment above: 1. Differentiate what is exposed to VNF vs what is not, 2. Avoid fragmentation by limiting implementation choices.

**Comment by tomkivlin** [comment]
From VF2F: @tomkivlin to link to PR being drafted, review this issue once that is raised.

**Comment by tomkivlin** [comment]
Closed due to inactivity.
