### ISSUE TITLE
[RM Ch04] Metrics to be considered

### ISSUE THREAD

**Issue by jeroenwittock** [cntt-n/CNTT#120]
Table 3-8: should contain max allowed packet drop rate?
Table 3-6: would it make sense to indicate whether HyperThreading has impact on performance (recommendation to enable or disable it)?

**Comment by xavier-grall** [comment]
For table 3-8 (and also table 3-14), that's right that network throughput metrics must be associated to some specific test conditions such as max allowed packet drop rate, but also frame/packet size and flow number. Moreover, those metrics, as well as latency-related and flow-related metrics, also depends on the path (eg N/S or E/W) and the processing type (eg w/ or w/o L4 statefull filtering) of the testing traffic. So, that relevant question implies another one :
Which metric test condition must be considered at which level (ie ref model, ref archi, ref implem or test program) ?

Regarding HyperThreading (or rather Simultaneous MultiThreading), it is related to NFVI HW profile (cf [chapter 6](https://github.com/cntt-n/CNTT/blob/1.0/doc/ref_model/chapters/chapter06.md)), and it could also be considered in table 3-6 as an NFVI capability, but probably with a different wording: for example, it could be a precision on the capability "cpu pinning" which would be either "no", "dedicated physical core(s)" or "dedicated logical core(s)". In that case, a new issue occurs because 2 different options are possible for C and N instance types, so we would have 2 variants of C and N instance types...
Anyway, that is another relevant question, which would require other opinions.

**Comment by xavier-grall** [comment]
For table 3-8 (and also table 3-14), that's right that network throughput metrics must be associated to some specific conditions such as max allowed packet drop rate, but also frame/packet size and flow number. Moreover, those metrics, as well as latency-related and flow-related metrics, also depends on the path (eg N/S or E/W) and the processing type (eg w/ or w/o L4 statefull filtering) applied to the traffic.
So, that relevant question implies another one :
Which metric associated condition must be considered at which level (ie ref model, ref archi, ref implem or test program) ?

Regarding HyperThreading (or rather Simultaneous MultiThreading), it is related to NFVI HW profile (cf chapter 6), and it could also be considered in table 3-6 as an NFVI capability, but probably with a different wording: for example, it could be a precision on the capability "cpu pinning" which would be either "no", "dedicated physical core(s)" or "dedicated logical core(s)". In that case, a new issue occurs because 2 different options are possible for C and N instance types, so we would have 2 variants of C and N instance types...
Anyway, that is another relevant question, which would require other opinions.

**Comment by kedmison** [comment]
Packet drop rate no longer referenced in RM documents

Hyperthreading is explicitly referenced in the NFVI profile types.

Thus, closing this issue as addressed.
