### ISSUE TITLE
[RA2 Ch04] Clarify Kubernetes Workload requirements

### ISSUE THREAD

**Issue by rihabbanday** [cntt-n/CNTT#1205]
The requirement stated in section **4.3**

`Workloads must not rely on the availability of the master nodes for the successful execution of their functionality (i.e. loss of the master nodes may affect non-functional behaviours such as healing and scaling, but components that are already running will continue to do so without issue)`

prevents the use of K8s CRDs and operators. Does this requirement have to be a "**must**"?

**Comment by tomkivlin** [comment]
I don't agree it stops the use of CRs and Operators.  As already stated, failure of the control plane would stop any changes to the state of _any_ resource that is managed by Kubernetes, including Custom Resources, but that doesn't mean the Custom Resource wouldn't continue to run/execute/be available (as per any other Kubernetes resource).

**Comment by tomkivlin** [comment]
PS - I've added to the Backlog as it's not affecting a chapter in scope of the Baldy release.

**Comment by rihabbanday** [comment]
I see, I thought there could be workloads that could depend on other attributes in the master node apart from healing & scaling. Nevertheless I think that is a workload requirement and not an infrastructure one. Good to have it in the Backlog.

**Comment by gkunz** [comment]
Coming back to this item: @tomkivlin isn't this a requirement on the workload rather than the platform? If that's the case, we should think about either removing it or rather moving it to a separate section which describes "best-practices" for workloads to make best use of the platform specified in RA2.

**Comment by tomkivlin** [comment]
VF2F: @CsatariGergely @tomkivlin @xmulligan to raise in TUG - maybe this should flow into the CNF Conformance program tests?  Need to consider that the Operator itself will be accessing the Kubernetes control plane and so the already-running Custom Resources will continue to run without issue, the Operator may through errors - e.g. do we need error handling tests in CNF Conformance?

**Comment by tomkivlin** [comment]
This section has been removed from ch04 since the issue was raised, and I think some clarity over the scope of RA2 with regards to workload requirements is now clearer (interoperability only - any best practice guidance such as this is to be agreed and dealt with in the new CNF working group in CNCF).
