### ISSUE TITLE
[RM Ch08] Move content of CH08 to RC

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#1331]
As discussed in TSM meeting, many/all content exist in RM Ch08 already covered by RC. @kedmison are you happy with the approach of moving the content away to RC-1?

**Comment by collivier** [comment]
A few contents are fully duplicated:
RM 8.3.2 Quality Assurance <-> RC 1.7 Assumptions & Dependencies
RM 8.3.1 Entry/Exit Criteria <-> RC 2.6 Entry & Exit Criteria

@rabi-abdel @kedmison 
About the first case, only one small sentence differs. Which one should I consider as base line? RC by default because we could consider it as a duplicate + very small updates of RM. No?

I would format the proposals as none are correct from a markdown point of view.
