### ISSUE TITLE
[RM Ch5] 5.2.1 Virtual compute metrics

### ISSUE THREAD

**Issue by SaadUllahSheikh** [cntt-n/CNTT#1466]
Suggest to consider following points 

1.CPU allocation ratio of basic profile 1:4 seems very aggressive suggest to update it as per Real VNF/CNF requirements 

2. Virtual RAM should be included

**Comment by pgoyal01** [comment]
@SaadUllahSheikh Ca you please review [5.2.1 Virtual Compute Metrics](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter05.md#521-virtual-compute) -- the CPU Allocation Ratio is now set to 1:1.

W.r.t. vRAM are you thinking that we need to specify an over-subscription of RAM?

**Comment by SaadUllahSheikh** [comment]
@pgoyal01  agreed on CPU , for RAM your understanding is correct .  as we know in a VNF context this is always 1:1 however in a CNF world vRAM over subscription is applicable .

E.g in 5G Standalone for NE like NERF it is definitely a possible scnerio , the point i wanted to raise is that for High performance or NW intensive ratio is 1:1 while for other i t can be 1:N

**Comment by SaadUllahSheikh** [comment]
@pgoyal01  kindly note in VNF it should be 1:1 based on all our experience the 1:N should only applicable for a CNF case

**Comment by pgoyal01** [comment]
@SaadUllahSheikh Thanks. Raises the question whether we should specify the values (for CPU, RAM and other allocations) in the RM as they will be different in the case of RA-1 and RA-2 or in some RA chapter(s). Moving to the RA chapters allows for different allocation ratios to be specified.

@walterkozlowski, @tomkivlin, @CsatariGergely, @karinesevilla, @cntt-n/ref-m Comments.

**Comment by walterkozlowski** [comment]
My suggestions to resolve this issue and close it:
1. Leave CPU allocation in Table 5-8 s the note in Notes column explains it is a guideline only for Basic profile.
2. Add RAM into the table for completeness but without values and in Notes explain that values will be different for different RAs and hence they will be defined there.
3. Raise Issues on RA-1 and RA-2 to specify the RAM over-subscription ratios there.
4. Remove a comment below Table 5-8 as it duplicates the Note, and in addition its reference is incorrect (it should be to infra.com.cfg.001)
@pgoyal01, @SaadUllahSheikh, @tomkivlin, @CsatariGergely, @karinesevilla, @cntt-n/ref-m - please comment.

**Comment by SaadUllahSheikh** [comment]
Agreed on this

**Comment by walterkozlowski** [comment]
@SaadUllahSheikh, thanks for agreeing to this.  @pgoyal01, do you agree as well?  If yes, could you raise a PR and do the changes sow e could close this Issue?  Thanks.

**Comment by pgoyal01** [comment]
@walterkozlowski Thanks. I think that more work would be required. We could clean-up the duplication in Chapters 4 and 5 (see below), or we can continue to maintain the status quo and make changes in multiple tables, for example,
-  add entry for RAM over-subscription in Tables 4.6, 4.19, 5-1 and 5-8; please note that in Chapter 4, the ref# for CPU Allocation Ratio is i.cap.006 while in Chapter 5 it is infra.com.cfg.001 (BTW the ref# are different in Chapter 4 and 5 for majority of capabilities)
-  in Table 4-18, the CPU Allocation Ratio for Basic is specified as 4:1 although the Note is identical to that in Table 5-8 and claims that it is set to 1:1

There are other items that need cleanup. Again for example, e.cap.006 CPU core pinning support in Table 4-2, CPU pinning support in Table 4-19, and CPU pinning capability in Tables 5-1 and 5-8. 

I think the question that first needs to be addressed is **whether it is necessary to redefine in Chapter 5 the capabilities already defined in Chapter 4**? Second, should we delegate specifying values for all of the capabilities to the RAs rather than just one or two?

**Comment by karinesevilla** [comment]
@walterkozlowski @pgoyal01 @SaadUllahSheikh 
In my opinion, we should first cleanup the duplicated tables in chapters 4 and 5 rather than start to modify the capabilties in multiple tables we will have to move at the end

**Comment by walterkozlowski** [comment]
Absolutely!

________________________________

**Comment by walterkozlowski** [comment]
Closed as per actions in the rm CLEANUP
