### ISSUE TITLE
[RM  Ch07]  NTP timing should be encrypted

### ISSUE THREAD

**Issue by tianliangma** [cntt-n/CNTT#1505]
7.5.1.2 The following general security requirements apply to the platform:
Data Centre Operations staff and systems must use management protocols that limit security risk such as SNMPv3, SSH v2, ICMP, NTP, syslog, and TLS. 

Obtaining NTP requires encrypted transmission to ensure the security of the clock

**Comment by karinesevilla** [comment]
@tianliangma 
Yes it can be added into recommendations

**Comment by karinesevilla** [comment]
@tianliangma , @walterkozlowski After the review of requirements, I think the issue is already covered by:

req.sec.gen.007 : All servers part of Cloud Infrastructure must be Time synchronized with authenticated Time service

req.sec.sys.003 : The Platform must support Secure and encrypted communications, and confidentiality and integrity of network traffic

There is no need to add another requirement

**Comment by walterkozlowski** [comment]
I agree with @karinesevilla and I am closing this issue.  It does not stop us from raising in the future new more specific issues around the time sync area.
