### ISSUE TITLE
[RM  Ch07]  NTP timing should be encrypted

### ISSUE THREAD

**Issue by tianliangma** [cntt-n/CNTT#1507]
7.5.2 Platform ‘back-end’ access security
Data Centre Operations staff and systems must use management protocols that limit security risk such as SNMPv3, SSH v2, ICMP, NTP, syslog, and TLS. 

Obtaining NTP requires encrypted transmission to ensure the security of the clock

**Comment by karinesevilla** [comment]
@tianliangma
Yes it can be added into recommendations

**Comment by karinesevilla** [comment]
@tianliangma , @walterkozlowski  After the review of requirements, I think the issue is already covered by:

req.sec.gen.007 : All servers part of Cloud Infrastructure must be Time synchronized with authenticated Time service

req.sec.sys.003 : The Platform must support Secure and encrypted communications, and confidentiality and integrity of network traffic

There is no need to add another requirement

**Comment by karinesevilla** [comment]
In addition to previous comment

Section numbering has changed. 
The original comment was related to "Platform ‘back-end’ access security" now section 7.4.2

In 7.4.1.2, we have: "All host to host communications within the cloud provider network are to be cryptographically protected in transit"
+ 
in 7.11, req.sec.gen.007 & req.sec.sys.003 described above

In my opinion, this issue is already covered and can be closed

**Comment by walterkozlowski** [comment]
Closed, as per comments from @karinesevilla and the RM WS decision on 12 August 2020
