### ISSUE TITLE
[RA-1 All] Consistency review of current chapters

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1574]
E2E review.

**Comment by walterkozlowski** [comment]
@pgoyal01, I started reviewing and I have found quite a few issues with Chapter 1 Overview, that I think it is better if I document them here, before passing to the next chapters. I tried to pretend to be a newcomer without any prior knowledge about this document or other CNTT documents.  
@rabi-abdel and @kedmison you may be interested in these observations as well, e.g. because of some unclear statements about versions and some issues with RM Principles which I discovered on my way.
Here we go:
Chapter 1 Overview

Comment #1: Acronyms and terminology: 
There is no information or consistency regarding the first use of acronyms: in some cases they are explained (e.g. QoS in the 1.2 “Performance tuning” use case) but most of them are not (e.g. GRE, MLAG in 1.3 “Overlay networks”). Most of them are very well known in the industry but we need to have a more consistent approach.  I suggest either define the acronym when it is first used in this document, or (better) make a comment at the beginning of the document that acronyms are defined in a glossary and provide a link to it.  In some special cases (I would not include QoS into this category) it may be done both ways; for example, when this is a new acronym introduced into the industry by this document.  
Looks like there are places where such definitions may be defined, Sec 1.3 Terminology refer to them but both links CNTT Reference Model and RA-1 Terminology DO NOT WORK (error 404).

Comment #2: Principles
Sec 1.4 uses link CNTT Reference Model Principles to the one sentence long Sec 1.3 in https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter01.md#1.3 with a link https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter01.md#1.3 when clicking on the latter on we land in Chapter 2 Principles in RM. It seems quite a convoluted way and the reader ends up two links from the original text, probably at lost.  A side comment: Sec 2.1 Overall Principles in RM need badly an update and refresh; e.g. Principle 9 explicitly forbids the use of SR-IOV (agreed when it uses PCI-PT but a nuance people may and will miss) while we have an exception process, which is not mentioned there. And few other issues (several of the principles are formulated like requirements not like principles, the text must be quite old by now).
Sec 1.4 uses also another link CNTT Reference Architecture Principles which takes us back to the GitHub landing page with links to two reference architectures (Openstack Based and Kubernetes Based); I think that most readers will be completely lost; also it is circular reference because selecting Openstack we are back in the document we started but in a different place..
Also, Sec 1.4: a minor typo: in bullet points describing Four Opens “design” is the only one which uses a small not a capital as the first character.
Btw: It seems we do not have any consistency writing OpenStack in some (most?) places and Openstack in others (see above).

Comment #3: OpenStack release
Sec 1.5 CNTT OpenStack Release: Shouldn’t it be “This Reference Architecture document in its current version conforms to the OpenStack Pike release.” Rather than the current “This Reference Architecture document conforms to the OpenStack Pike release.” Later on we read ‘For ease, this CNTT Reference Architecture version can be referred to as "RA-1 OSTK Pike."’  We need to be clear whether we are talking about the document, about the architecture or about a version (of what? Of a document? Or of Architecture?).

Comment #4: Document Organisation
The first sentence of Sec 1.6 is “The Reference Architecture requirements and the traceability where in this document the requirement is addressed is documented in Chapter 2.” contains a typo “is addressed is documented”. The traceability part of this sentence is a bit unclear, particularly as in Chapter2 Sec 2.2 “Reference Model Requirements” we have only one sentence “Traceability to Reference Model.” and that’s it!  Back to the first sentence of Sec 1.6:  I would propose something like “ Chapter 2 defines the Reference Architecture requirements and, when appropriate, provides references to where these requirements are addressed in this document.”
Typo: “items, Please note that”, should be “items. Please note that”.
The sentence “Chapter 8 identifies certain Gaps that currently exist and plans on how to address them.” is a bit misleading as Chapter 8 only make a promise to do such plans saying “Once gaps are identified, the next step will be to propose a plan to address these gaps.” and indeed Chapter 8 does not provide such plans yet (except of some hints what might be possible or not, in some cases; no such hints in other cases).
Btw: why “Gaps” in Sec 1.6 (capital “G”) and “gaps” (small “g”) in Chapter 8?

**Comment by rabi-abdel** [comment]
Really Great review @walterkozlowski 
Added @bfcohen to the conversation to see if we can get some of those fixed for baldy as well.

**Comment by pgoyal01** [comment]
@walterkozlowski Great review and feedback. I have fixed the links issue although the Terminology file is currently empty.

Have fixed all of the identified issues in Ch01.

W.r.t. "Traceability to Reference Model" -- the requirements in RM need to be made consistent in terms of their numbering scheme, duplicates deleted, etc. There are issues open in both RM and RA-1 (for when RM fixes their requirements) to fix the same.  I had provided examples of many issues in the RM chapters months ago but they are yet to be addressed.

Thanks for great feedback.

**Comment by pgoyal01** [comment]
@rabi-abdel can the corrections - PR #1595 (and linked issue $1594) - during proof reading be included in the Baldy release? Proof reading updates can be made until midnight UTC

This Issue #1574 can continue to be used for the E2E review.

**Comment by walterkozlowski** [comment]
E2E review - next installment.
Chapter 2 Architecture Requirements ( sec 2.1 - 2.3.1)
Comment #1 
Section 2.1 Introduction
What does note “RFC2119” mean?
It is unclear what is the difference between Requirements using “may” (or “may not”) and Recommendations. Section 2.1 says:
may: Requirements that are marked as may are considered optional. The same applies to may not.
This chapter includes both "Requirements" that must be satisfied in an RA-1 conformant implementation and "Recommendations" that are optional for implementation.
Was the intent here to distinguish between Requirements that are traceable within this document and Recommendations that are not (are of more general nature)?  Some Requirements though are stated like general Recommendations  and are not traceable to anything tangible within RA-1 document, e.g. req.gen.rsl.01 Resiliency.

Comment #2 
Section 2.2. Reference Model Requirements
This section contains only 4 words (Traceability to Reference Model.).  What is the real purpose of this section?  It needs to be clarified/fixed.

Comment #3
Sec 2.3.1 General Requirements
Requirement “req.gen.rsl.01 Resiliency” without traceability or clarification is not testable.  In the current form it is rather a general Recommendation (see Comment #1). 

Comment #4
Sec 2.3.1 Infrastructure Requirements
Requirement “req.inf.com.05” (NUMA), the traceability link does not work (Error 404)
Requirement “req.inf.com.07” (different hardware configurations), the traceability link does not take the reader to Sec 3.3.3 as promised but to Chapter 3; Looks like Sec 3.3.3 has now a different title than in the traceability column for this requirement.  Shouldn’t be this link rather traceable to 4.4.1? 
Requirement “req.stg.com.04” (SDS) Are we saying (by linking to 4.2.4.1) that if someone wants to uses SDS (this is “may” requirement) they must use Ceph?  I am not questioning if this is the case (as OpenStack definitely recommends Ceph) but this is actually unclear.  Are we allowing other SDS like Gluster? I would not think so.  We need to ake it very clear.
Requirement “req.stg.com.05” is missing.  Need to add it with a note “Deprecated” (or equivalent).  Unless of course it is a genuine requirement which has been lost somewhere.
Requirement “req.stg.com.07” similar comment to “req.stg.com.04”
Requirement “req.inf.com.15” The link to Sec 4.2.3.4 does not work, it looks like this section change its name
Requirement “req.inf.acc.01” “The Architecture should support Application Specific Acceleration (exposed to VNFs).” This must be confusing for the readers, and the text in 3.2.6 does not help.  What are we really trying to say they “should” do here?

**Comment by iangardner22** [comment]
**Here is my review of the intro and chapter 1**

- (Minor formatting) **Overall status** table doesn't reflect the individual chapter _Bogo-meters_
- **CNTT** - in the next release we may wish to start to move away from what is a 'short-term definition. Perhaps it will just be a global find/replace as I know it is convenient to use "CNTT" for now until we have a permanent name!  @rabi-abdel your views?
- 1.2 This section is currently a copy and paste of a section of OpenStack.org so I wonder if instead we list some real example VNF use cases and the capabilities they expect the OpenStack architecture to provide by default.  For example for predictable low packet loss VNFs such as RAN, IMS, VoLTE it may be necessary to use data centre VLAN provider networks with DPDK and pin CPUs where as for non packet intensive OSS tooling workloads we can use DNAT/SNAT and RFC1918 addressing.    We have a lot of operators in CNTT who can share what they are doing with their deployments - I think these would be better use cases than listing what are capabilities from openstack.org docs. 
- 1.4 - (Minor formatting) Suggest to match the case on the second word in the four O's - 'design' stands out.
- 1.4 - I suggest in this section we downplay the GUI as we really need to call out in the principles that the platform supports highly automated IaC (infrastructure as code) as opposed to human _click to provision_ operations of days gone by.  Sure the GUI is useful for validation and some specific admin things but for me it's less important if we want to change gears into true Cloud scale operations.
- 1.6 - a long paragraph could be replaced with a table for simplicity.

<end>

**Comment by iangardner22** [comment]
**Here is my review of the intro and chapter 2**

- (minor formatting) I would get rid of the must and should and just use bold text in the main paragraph.  
- Again minor but we should be clear with **_must not_** and **_should not_** that the same **(yet opposite)** applies in these cases - it doesn't quite read correctly currently being really picky here.  
- There appears to be a floating RFC2119 - not sure where this came from!
- 2.3.1 Resiliency.  I read this as the infrastructure must be deployed in HA manner.  This can link to 3.5 Cloud Topology which sets this out.   Resiliency of the VNF is the VNF or VNFMs concern.
- 2.3.1 - I think req.gen.avl.01 is actually mapped to the wrong section and this should also be 3.5 
- 2.3.2 - This is talking about OpenStack services as opposed to workloads being pinned I think so perhaps here we need something about PMD cores and Hypervisor threads?
- 2.3.2 - req.inf.ntw.16 and 17 - this should be something @ildikov can help to answer any limitations and if we have then we should address in Ch8.
- 2.3.6 - I think we need to acknowledge that a major upgrade WILL take out a control plane even if its for a small period of time.   Not sure where to capture this.
- 2.x.x- General point: any gaps in this section either need a section adding to ch3,4,5,6,7 or we need to put them into Gaps and describe what we are doing with OpenStack Foundation to resolve them.   An issue needs to be raised for every missing traceability 'must' and ideally every 'should'
- 2.x.x - Perhaps where we have gaps we call out the implication of not meeting it too.

I move on to Ch3 and later when I find time.
