### ISSUE TITLE
[RM Ch04] Section 4.2.6 Cloud Infrastructure Profile Performance Measurement Mapping

### ISSUE THREAD

**Issue by ASawwaf** [cntt-n/CNTT#1582]
4.2.6 Cloud Infrastructure Profile Performance Measurement Mapping

Comment: To be worked on.

This section is under development, can we figure out the purpose of this section

**Comment by CsatariGergely** [comment]
We need to figure out if this chapter is needed at all and if yes what it should contain.

**Comment by pgoyal01** [comment]
@walterkozlowski for this to be "In Progress" it would need an associated PR but none exists

**Comment by pgoyal01** [comment]
@ASawwaf  asks we need to "figure out the purpose of this section." 

Since the creator of this section was not clear in the intent, I can only hazard a guess. It would be to take the entries from Table 4-11 and create a table similar to Table 4-17 specifying acceptable values for each of the measures in Table 4-11 for the Basic and Network profiles. Not sure where we would get these values from.


Ref | Cloud Infrastructure Management Measurement | Unit | Basic | Network Intensive | Notes |
-- | -- | -- | -- | -- | -- 
e.man-pm.001 | Time to create Virtual Compute resources (VM/container) for a given workload | Max ms |   |   |   |
e.man-pm.002 | Time to delete Virtual Compute resources (VM/container) of a given workload | Max ms |     |   |   |
e.man-pm.003 | Time to start Virtual Compute resources (VM/container) of a given workload | Max ms |     |   |   |
e.man-pm.004 | Time to stop Virtual Compute resources (VM/container) of a given workload | Max ms |     |   |   |
e.man-pm.005 | Time to pause Virtual Compute resources (VM/container) of a given workload | Max ms |     |   |   |
e.man-pm.006 | Time to create internal virtual network | Max ms |     |   |  what is "internal virtual network"? |
e.man-pm.007 | Time to delete internal virtual network | Max ms |     |   |   |
e.man-pm.008 | Time to update internal virtual network | Max ms |     |   |   |
e.man-pm.009 | Time to create external virtual network | Max ms |     |   |  what is "external virtual network"? |
e.man-pm.010 | Time to delete external virtual network | Max ms |     |   |   |
e.man-pm.011 | Time to update external virtual network | Max ms |     |   |   |
e.man-pm.012 | Time to create external storage ready for use by workload | Max ms |     |   |  What does this mean? "creating" the storage array or the block of storage requested for the workload or ... ? |

My comments/questions also apply to Table 4-11.

**Comment by pgoyal01** [comment]
As per meeting of July 29, 2020, Section 4.2.6 will be deleted (kept but title changed). RA1 and RA2 will be notified by @walterkozlowski to include the above performance table in their specifications
