### ISSUE TITLE
[RC2] Add API benchmarking conforming to RC1

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#1745]
Functest includes xrally_kubernetes which allows benchmarking the API as CNTT asks vs OpenStack (RC1).
The model will conform to RC1. If there is no KPI defined in RA2, the default SLA (maximum failure rate of 0%) will be proposed.
https://github.com/cntt-n/CNTT/blob/master/doc/ref_cert/lfn/chapters/chapter03.md

It's worth mentioning that the existing test case already fits the CNTT test case integration requirements.

**Comment by collivier** [comment]
I put it on my agenda.
Of course any help (especially from Nokia which masters this test case via Functest and Akraino) is more than welcome to release my Baraque schedule.

**Comment by taylor** [comment]
@collivier I'm not sure of what is being suggested here.  Do we create a RC2 chapter similar to https://github.com/cntt-n/CNTT/blob/master/doc/ref_cert/lfn/chapters/chapter03.md but which lists K8s APIs instead of OpenStack APIs?  

Also, where are the tests cases and what are the requirements mentioned in:

"It's worth mentioning that the existing test case already fits the CNTT test case integration requirements."
