### ISSUE TITLE
[RM Ch07] 7.11.1. System Hardening

### ISSUE THREAD

**Issue by zwarico** [cntt-n/CNTT#1884]
General question about the section: Are "Platform" and "Cloud Infrastructure" interchangeable terms? Where can I find the definitions?

**sec.gen.001**
**Current Requirement:**
The Platform **must** maintain the state to what it is specified to be and does not change unless through change management process.

**Proposed Modification:**
The Platform **must** maintain the specified configuration.

**Proposed Additional Requirement:**
Any change to the Platform **must** be logged as a security event, and the logged event must include the identity of the entity making the change, the change, the date and the time of the change.

**Reason:**
Change management is a process to track the changes made to a component. It is external to the Platform. There needs to be a log of all Platform configuration changes

**sec.gen.002**
**Current Requirement**
All systems part of Cloud Infrastructure must support password hardening (strength and rules for updates (process), storage and transmission, etc.)

**Proposed Modification**
All systems part of Cloud Infrastructure must support password hardening as defined in NIST Special Publication 800-63B (June 2017 with 3 March 2020 Updates.)

**sec.gen.004**
**Current Requirement**
The Operating Systems of all the servers part of Cloud Infrastructure must be hardened

**Proposed Modification**
The Operating Systems of all the servers that are part of the Cloud Infrastructure must be hardened by removing or disapling unnecessary services, applications and network protocols, configuring operating system user authentication, configuring resource controls, installing and configuring additional security controls where needed, and testing the security of the Operating System (see NIST Special Publication 800-123).

**sec.gen.010**
**Question**
What is meant by Secure "storage (all types)"

**Comment by walterkozlowski** [comment]
@karinesevilla, what is the status of these requirements?

**Comment by karinesevilla** [comment]
@zwarico Thank you for your review and relevant proposals
Cloud infrastructure is defined  in https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter03.md#31-model
Platform and Cloud Infrastructure are the same within the security requirements.  Platform is not defined, I totally agree, the ongoing  PR#1882 partially solves this.
Sec.gen.001: good proposal
For sec.gen.002, in RA1 we decided to use the CIS password policy guide as a reference (https://www.cisecurity.org/white-papers/cis-password-policy-guide/). It should be added in RM as well.
sec.gen.004: good proposal, much more detailled
sec.gen.010: I think it means storage encrypted for Block, objet and file storage
Amy, feel free to create a PR to modify these requirements

@walterkozlowski The modifications suggested by Amy are in line with the work we need to do in order to make the requirements more 
understandable

**Comment by pgoyal01** [comment]
@zwarico @karinesevilla the terms platform and cloud infrastructure are defined in the [Glossary](https://github.com/cntt-n/CNTT/blob/master/doc/common/glossary.md):
- under the heading "[Other Referenced Terminology](https://github.com/cntt-n/CNTT/blob/master/doc/common/glossary.md#other-referenced-terminology)", "Platform: A cloud capabilities type in which the cloud service user can deploy, manage and run customer-created or customer-acquired applications using one or more programming languages and one or more execution environments supported by the cloud service provider ([ITU](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-Y.3500-201408-I!!PDF-E&type=items))."
- under heading "[Software Layer Terminology](https://github.com/cntt-n/CNTT/blob/master/doc/common/glossary.md#software-layer-terminology)", "Cloud Infrastructure: A generic term covering NFVI, IaaS and CaaS capabilities - essentially the infrastructure on which a Workload can be executed."
