### ISSUE TITLE
Tenant Definition different [Chapter 1] and {Chapter 3]

### ISSUE THREAD

**Issue by bfcohen** [cntt-n/CNTT#204]
Tenant is defined in Chapter 1 and in Chapter 3 are different. Which one should we consider here? Need to define the tenant in more detail and reconcile the differences.
JB - Clarifications needed. Slicing vs. Tenant, etc.
After the definition is done use the definition in a consistent way. BFC -- Agreed.
Related to #197 and #194

**Comment by BernardTsai-DT** [comment]
When defining a tenant in the context of this document I would propose to focus on the infrastructure related aspects of this entity and decouple it's definition as much as possible from any organizational aspects since these will differ between operators. 

In this sense I would propose to update the definition in chapter 1 in the following way:

Tenants represent an independently manageable pool of virtual compute, storage and network resources.

**Comment by pgoyal01** [comment]
Chapter 1: Tenant: represents an independently manageable pool of virtual compute, storage and network resources.

Chapter 3: Tenants: represent an isolated and independently manageable elastic pool of compute, storage and network resources

@bfcohen Could you align with Chapter 3 as it captures certain essential elements such as "isolated" and "elastic pool"? Thanks.

**Comment by BernardTsai-DT** [comment]
This issue has already been addressed in issues: #194 and #197.
