### ISSUE TITLE
[RA1 Ch08] Develop a standard hw acceleration interface

### ISSUE THREAD

**Issue by rabiabdel** [cntt-n/CNTT#373]
There is a need to start developing standard hardware interfaces for acceleration such as crypto, ipsec, and get it upstreams into the right projects.

**Comment by sukhdevkapur** [comment]
This issue is addressed as part of issue #372. This is a gap in the openstack, and it is listed under packet acceleration gap. Once we review and agree with the gaps identified at the F2F meeting in Prague, we will come up the plan to implement this interface and work with upstream communities to get it incorporated
