### ISSUE TITLE
[RM Chap04] Section 4.2.5 Incorrect values on table 4-24

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#385]
Table 4-24 "Mapping of NFVI capabilities", some values are wrong:
For C instance, NUMA support and Huge Pages must be "Yes"

**Comment by markshostak** [comment]
Per weekly RMCH-4 review meeting, the following changes have been proactively approved by the review team, and will be implemented by a forthcoming update by Karine:
- Table 4-24: For Instance Type C, NUMA (e.nfvi.per.cap.002) is changed from NO -> YES
- Table 4-24: For Instance Type C, Huge Page Support (i.nfvi.per.cap.001) is changed from NO -> YES
- Table 4-24: Row i.nfvi.mon.cap.005 (External storage IOPS) is DELETED
- Table 4-24: Row i.nfvi.mon.cap.006 (External storage throughput) is DELETED

**Comment by markshostak** [comment]
Reassigned to Karine, per agreement in chapter review mtg.

**Comment by markshostak** [comment]
Hi Karine (and Mike and Kelvin), I agree those caps have been relocated. However, the purpose in having them in the mapping table is so VNF developers can determine what kind of protection a given Instance Type (IT) will be afforded. As it happens, the flags are the same for all ITs, but I think we should get some more input before we rip them out. RMCH-7 does not provide mapping or indication of capability availability, therefore the indication either needs to be added to CH-7, which breaks the 1 stop shop design intent of the RMCH-4, or it needs to be handled somewhere else (e.g., some language added to CH-4 outside of the table). 

@mbustame and @kedmison, can you give us your input on where best to rehome these flags pls? Thx, -Mark

P.S. We also need to assess how containers impact the flags. They sound somewhat VM-specific, and if that's true, we need to rehome them into RA1.

Net-net, please don't rip them out until we've settled on where to put them.

**Comment by kedmison** [comment]
In thinking about this, I've actually come around to the perspective of leaving these in the model.  

We should assume that every OpenStack Reference Architecture would have the same answer for all 3 of these items, regardless of flavour,  and when considering Openstack I can see the argument for how it's so intrinsic as to be known implicitly. 
However, I am not sure we can say the same when it comes to the Kubernetes reference architecture.
Most container runtimes, right now, do not create a strong security partition between adjacent containers, so other mechanism are used as crutches to provide those security guarantees/tenant boundaries.  Options for creating this boundary include using different VMs, or different bare metal machines, or different K8S clusters entirely, or some of the new container runtimes that leverage virtualization instructions, but none of these strategies is explicitly required when deploying a vanilla Kubernetes cluster.  
I would like to see a discussion in the RA as to whether we are mandating this sort of security partitioning for all Kubernetes RAs and RIs (a reasonable statement for them to make, but it should be explicitly done).  If they do, then I think we still keep them in to show that at the high level model as applied to Kubernetes ensures these security guarantees are provided, rather than leaving it implicit and CNF authors having some limited container knowledge and thinking these concerns are not addressed.
If they do not make the statement, then I think we have to remove these items as we cannot document, at a model level, consistent characteristics for this security partitioning.

**Comment by markshostak** [comment]
Fixed by merged PR referenced above - closing. -M
