### ISSUE TITLE
[RM Ch05] Make object storage optional

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#524]
Section 5.2.2 Virtual Storage: I think "Object Storage"s should be optional

**Comment by markshostak** [comment]
@pgoyal01 Optional in specifically what sense? Object storage is optional. Just because it's supported for a given Instance Type, doesn't mean a developer has to use it.

**Comment by pgoyal01** [comment]
@markshostak OpenStack Swift is optional service -- operators may not (and some do not) deploy it in their environments.

**Comment by kedmison** [comment]
Object storage is currently marked as required in the RM (certainly open for discussion as to whether that's correct).  
However, from a VNF vendor perspective, if they develop a VNF that depends on Swift for a particular function, what is CNTT recommending the VNF vendor do when they encounter a NFVI that does not deploy Swift?   Is the VNF vendor precluded from deploying there, and must re-architect their VNF to not use object storage?  Is the VNF vendor expected to bring their own object storage implementation that sits on top of the existing block storage service?

**Comment by pgoyal01** [comment]
@kedmison Great point.  If RM is to insist on object storage as required -- needs to justify why -- then obviously the RA's will have to make it mandatory also to be compliant with the RM.

Object storage is a PaaS service, as I think you had mentioned previously. Should the RM be specifying PaaS services?

**Comment by deebhatia** [comment]
@pgoyal01 Referring to [this](https://object-storage-ca-ymq-1.vexxhost.net/swift/v1/6e4619c416ff4bd19e1c087f27a43eea/www-assets-prod/openstack-map/openstack-map-v20191001.pdf) landscape diagram of OpenStack, OpenStack does treat swift as a core functionality. It is present at the openstack overview [page](https://www.openstack.org/software/).
If we see swift being used for service based use cases like glance storage backend, cinder volume snapshot backups then service can be part of the whole ecosystem but the PaaS functionality (Object Storage feature) is a bonus offering which is optional.

**Comment by ASawwaf** [comment]
@deebhatia @pgoyal01 @markshostak Sure it is core in Openstack , but in a real implementation, not all operator go with Swift, opposite to cinder it is required for all VNF vendors 

So my POV , let put it as optional in RM and should be reflected in RA01

**Comment by kedmison** [comment]
I think we are running into a difference of expectations for an NFVI-only platform vs. a platform that can support NFVI and IT and ML workloads.  

I agree that traditional data plane VNFs may not have a need for Swift, but the sorts of management and back-office applications that come with managing networks would indeed benefit from having it as they often have characteristics more closely aligned with IT workloads than NFV workloads.

Swift is often used in IT and ML workloads.  It's a very convenient and efficient way to store and share large amounts of data without requiring that an application instantiate a VM and consume RAM and CPU, waiting for an occasional request.  It can also be used as a data hand-off point.  

If we choose to mark it a major API like Object store as optional, then it won't be used as the VNF vendors can't rely on it to be present and so will avoid the use of Swift at all in order to design VNFs that are applicable everywhere...at the cost of increased NFVI resource usage.

**Comment by collivier** [comment]
-1 to put swift as Optional

**Comment by kedmison** [comment]
@pgoyal01 @ASawwaf @deebhatia @markshostak @karinesevilla 
This issue has been stalled for a while, and needs to be concluded.  What are everyone's opinions?  to close it (and leave Swift as mandatory?) or to push through a PR to make Swift optional?

**Comment by pgoyal01** [comment]
@kedmison I think this was previously mentioned by someone. CNTT NFVI is an IaaS platform whereas "Object Storage" is a PaaS service. More importantly, why are storage types being associated with Instance types in RM 5.2.2? 

In 5.1.2. a Catalogue of storage types is defined -- can be any storage type in the catalogue but is not specified and then made mandatory in 5.2.2 -- mandatory without knowing what is in the catalogue.

**Comment by kedmison** [comment]
Object storage is a very common service.  Yes, it can be considered a PaaS service but it's a very basic building block.  If it stays in it would be a PaaS storage service separate from the block storage services being defined... and thus not associated directly with an instance type.
