### ISSUE TITLE
[RA-1 Ch03] 3.5. Deployment Models | Need Content

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#638]
[RA-1 Ch03] 3.5. Deployment Models | Need Content

**Comment by iangardner22** [comment]
Here I see the different topologies we should recommend including the CLOS network.

So:
Single Region: 
- single site, single AZ
- dual building at same site, two AZ
- edge

We should also show what is not shared between the AZs e.g. block storage

I will assign this to me

**Comment by kedmison** [comment]
Here are some rough thoughts on Availability Zones: 
- Having an AZ story will be very helpful to VNF vendors. 
- Not having this abstraction can lead to over-use of anti-affinity features, leading to suboptimal/inefficient workload placement
- It may not need to be a consistent lineup of independent failure domains (e.g. independent buildings) across all CNTT-compliant implementations, as long as the NFVI operator can to the VNF purchaser an acceptable scoping of failure domains to AZ abstraction.
  - e.g. one operator may choose to create their AZ abstraction as independent servers, independent racks, independent TOR switches, independent circuits, but same cooling, same building, same utility power feed... whereas another operator may choose to create their AZ abstraction as independent racks, TOR, circuits, cooling, utility feed, but not building.  
- A consistent framework for NFVI operators to document the failure domains of an AZ may be a helpful output of the CNTT.

Many cloud-native systems these days are based on quorums.  When considering AZs, the needs of quorum-based systems should be considered (e.g. minimum 3 AZs rather than 2)

**Comment by iangardner22** [comment]
@kedmison totally agree as with two AZ we get the risk of split-brain for the application...  for the control plane we could run fewer controllers in one location e.g. 2+1 stretched which would force a manual intervention in the event of building loss - but I'd be interested from the OpenStack vendors (including Nokia :-) ) on the recommended approach.

**Comment by ASawwaf** [comment]
@kedmison @iangardner22 @iangardner22  , AZ and HA ( Host Aggregate ) is very important to adopt it  
HA can be per type of HW type , VNF vendor, VNF profile ,..

For the Networking part , The IP CLOS or Fabric will be the main deployment for networking associated with SDN-C

**Comment by iangardner22** [comment]
This had fallen in to the Archive @pgoyal01 - do you agree this should move back to To Do?

**Comment by pgoyal01** [comment]
@iangardner22 Yes please

**Comment by iangardner22** [comment]
So currently document out for review before I add as a PR...  @pgoyal01 thanks for your v2 feedback - please see my feedback v.21 and let me have your feedback :-)

**Comment by iangardner22** [comment]
Please keep this open.  @kedmison is reviewing internally and once complete a PR will be raised to put this section out for wider review.
