### ISSUE TITLE
[RA-1 Core] Clear definition of tenant(wrt multi-tenancy) and OpenStack tenant/project

### ISSUE THREAD

**Issue by msidana** [cntt-n/CNTT#666]
In RM, the term tenant is being used in [this](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter03.md#3.2.1) section. This becomes confusing when referring to OpenStack as there is a mixture of usage - tenant and project.
We should have a clear definition of tenant as CNTT tenant that refers to multi-tenancy and the usage of project should be encouraged when referring to OpenStack (since we are using v3). [This](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/glossary.md#1113-operational-and-administrative-terminology) section says ```Tenants represent an independently manageable logical pool of compute, storage and network resources abstracted from physical hardware.```. Why does it says "abstracted from physical hardware." (in context of ironic we cna have bare metal provisioned) ? 
We also need to define 
1. Clear Definition of tenant, project, logical entities in multi-tenancy
2. A mapping of CNTT tenant with both OpenStack and Kubernetes. For example
Customer(A better word here) = CNTT Tenant  = OpenStack Project = Kubernetes XYZ (some term instead of XYZ)

I have tried to do something in https://github.com/cntt-n/CNTT/pull/662/
Thoughts
@iangardner22 @pgoyal01 @rabi-abdel @tomkivlin @karinesevilla @deebhatia 
If you agree, we can create issues in RM and RA and have a clear usage of these terms

**Comment by pgoyal01** [comment]
@msidana IMHO, the definition holds even with containers on bare metal, the objects Pods, containers etc. are abstractions. Even a kubernetes node is an object and a representation of a physical server.

**Comment by deebhatia** [comment]
@pgoyal01 The query is raised here due to mix up in Openstack tenant and CNTT tenant terminology in Ch03. We will be using Pike and Keystone V3, which uses the `project` terminology instead of `tenant`. Since v2 is not to be included, tenant terminology usage referring to OpenStack tenants should refer to OpenStack projects instead.
**For example**: [here](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter03.md#321-tenant), the example should contain the text as `an OpenStack project or a Kubernetes cluster.` instead of `a tenant within an OpenStack environment or a Kubernetes cluster.`

**Comment by tomkivlin** [comment]
As with other terms, I prefer to have an authoritative reference to use, rather than spending cycles wordsmithing a definition ourselves.  The [ITU](file:///Users/kivlint/Downloads/T-REC-Y.3500-201408-I!!PDF-E.pdf) uses the following definitions, would they suffice for the RM and both RAs?

> **multi-tenancy**: Allocation of physical or virtual resources such that multiple **tenants** and their computations and data are isolated from and inaccessible to one another. 

> **tenant**: One or more cloud service users sharing access to a set of physical and virtual resources.

Alternatively, the [ETSI NFV definition](https://www.etsi.org/deliver/etsi_gs/NFV/001_099/003/01.04.01_60/gs_nfv003v010401p.pdf) is adapted from the above:

> **tenant**: one or more NFV-MANO service users sharing access to a set of physical, virtual or service resources
NOTE 1: This definition has been specialized from the term "tenant" as defined in Recommendation ITU-T Y.3500 [i.7].
NOTE 2: The "tenant" concept in NFV should not be confused with the "tenant" (aka "project") concept in OpenStack. The OpenStack implementation covers a subset of the overall functionalities required by multi-tenancy in NFV. 

My preference would be the ITU definition, as it is more generic and doesn't constrain us to MANO users but any consumer of the architectures.

Thoughts?

**Comment by msidana** [comment]
@tomkivlin +1 for ITU definition(as it will give am independent perspective to CNTT docs without any other assumption) with a strong emphasis that the term "tenant" should not be used anywhere when referring to keystone and the term "tenant" not to be used/mixed while talking about OpenStack. For Openstack we can specify that tenant(ITU) translates into a project(keystone v3).

**Comment by tomkivlin** [comment]
Yes agree, the note from the ETSI version could be useful even if we use the ITU one.

**Comment by mf4716** [comment]
@tomkivlin - +1 also for ITU definitions as well, straight forward, with clear identification of shared infra/software, but also isolation between tenants across these resources, without directly associating MANO needs, or capabilities.   In favor of the ITU def.

**Comment by pgoyal01** [comment]
@tomkivlin @msidana the ETSI definition broadens the ITU definition to more then "cloud users" and can be uesful. If going with ETSI, then 
 
**multi-tenancy**: feature where physical, virtual or service resources are allocated in such a way that multiple tenants and their computations and data are isolated from and inaccessible by each another
NOTE: This definition has been specialized from the term "multi-tenancy" as defined in Recommendation ITU-T Y.3500 [i.7].

ETSI treats multi-tenancy as a "feature" rather than just an "allocation of resources" -- a subtle but significant distinction.

**Comment by tomkivlin** [comment]
@pgoyal01 I see the ETSI definition of **tenant** constraining it to MANO users, rather than broadening it.  However, I do like the ETSI definition of **multi-tenancy**.

If I had to vote now, I would go ETSI for **multi-tenancy** and ITU for **tenant**.

**Comment by deebhatia** [comment]
+1 for ETSI for **multi-tenancy** and ITU for **tenant**.

**Comment by msidana** [comment]
This sounds good. @tomkivlin @pgoyal01  If we are able to build a concensus on it, then we may create issues on GitHub to introduce fixes across all documents - RA, RM etc wherever these definitions are being used.

**Comment by pgoyal01** [comment]
@tomkivlin ETSI considers VIM as part of MANO. I am OK with the ITU definition but maybe we can define "cloud user" (include applications as users also).

**Comment by tomkivlin** [comment]
> ETSI considers VIM as part of MANO

Aye, but what about a k8s control plane?

> maybe we can define "cloud user" (include applications as users also)

Yes, agreed that would be a good idea.

**Comment by iangardner22** [comment]
+1 @tomkivlin 

So long as we have a clear 1:1 mapping for what this translates to in keystone (i.e. project) I see no problem.

**Comment by rabi-abdel** [comment]
@msidana is PR: #662 trying to Fix this issue? I suggest do the change you propose here into there as well. so we don't have to go back and forth in terms of issues creation. I suggest @msidana to introduce the changes proposed/agreed on directly on #662

**Comment by msidana** [comment]
> @msidana is PR: #662 trying to Fix this issue? I suggest do the change you propose here into there as well. so we don't have to go back and forth in terms of issues creation. I suggest @msidana to introduce the changes proposed/agreed on directly on #662
@rabi-abdel 
Since #662 belongs to RA1, I have used the term project (v3) and also stated a difference between tenant and project w.r.t OpenStack. 
I have used it in an unambiguous way in #662 so it doesn't introduces any issues.
Fixing for https://github.com/cntt-n/CNTT/issues/666 will require changes in RM and we might need to revisit Chapter 3 RA1 (already merged section)

**Comment by msidana** [comment]
@rabi-abdel 
Since #662 belongs to RA1, I have used the term project (v3) and also stated a difference between tenant and project w.r.t OpenStack. 
I have used it in an unambiguous way in #662 so it doesn't introduces any issues.
Fixing for https://github.com/cntt-n/CNTT/issues/666 will require changes in RM and we might need to revisit Chapter 3 RA1 (already merged section)

**Comment by pgoyal01** [comment]
Created PR #758 :: [RM Glossary] Added Cloud User (ITU), Tenant (ITU; made existing a Note), and Multi-tenancy (ETSI) per discussion in Issue #666.

Need review and Fixes of content in all RM, RA-1 and RA-2 chapters to be consistent.

**Comment by pgoyal01** [comment]
PR #758 merged.
