### ISSUE TITLE
[RM Ch01] RM principles don't include any rationale or implication statements

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#739]
Also the tense is not consistent and some read as requirements rather than principles.

**Comment by markshostak** [comment]
@tomkivlin Hey Tom, To make the rationale and Principles consistent, do you want to have a Principle template? I'm envisioning something like:
- Title
- Body
- Scope // if applicable
- Rationale

**Comment by tomkivlin** [comment]
@markshostak yes what I had in mind was:

|Ref#|Principle|Statement|Rationale|Implication|
|---|---|---|---|---|
|||||

What do you think?

**Comment by tomkivlin** [comment]
@markshostak to expand, sorry should have done so. The Principle field would be the "title " and the Statement field the "body", to map to your suggestion.

**Comment by markshostak** [comment]
> 
> 
> @markshostak yes what I had in mind was:
> Ref# 	Principle 	Statement 	Rationale 	Implication
> 				
> 
> What do you think?

@tomkivlin Hi Tom, 2 thoughts:

1) Is your intent for Implication that could cover what I called [Scope]?; basically something to indicate if the Principle's applicability is focused on a specific area (plus other uses)? What are the other uses you're thinking of?

2) I agree we need a table w/ Ref#s to normalize the Principles, but I think we still need to list some or all of them out in a bulleted format in order to make it effective (i.e. when we say "the APIs need to be open and components need to be substitutable", it needs to be big and bold so no one misses it, and not just buried in the middle of a table). In other, the bullets are the billboard, and the table is the "fine print". Make sense? 

Thx,
-Mark

**Comment by tomkivlin** [comment]
@markshostak I would normally add the scope into the statement and use the implication to list the impact this principle might have on either the topic in question or guidance on how to adhere to it.

OK, understood re. list v table - I think if we're strict on the difference between Principle and Statement that may help with an easy-to-consume list as we can refer to "the <principle name> principle".

At risk of teaching you to suck eggs, here is an example (really is just an example):

|Principle|Statement|Rationale|Implication|
|---|---|---|---|
|Fewer Architectures|Minimise the proliferation of Reference Architectures [_the scope_] by stipulating that compatible features are contained within a single Reference Architecture.|yada|<ul><li>Features which are compatible, meaning they are not mutually exclusive and can coexist in the same NFVI instance, shall be incorporated into the same Reference Architecture. For example, IPv4 and IPv6 should be captured in the same Architecture, because they don’t interfere with each other.</li><li>Focus on the commonalities of the features over the perceived differences. Seek an approach that allows small differences to be handled at either the low-level design or implementation stage. For example, assume the use of existing common APIs over new ones.</li></ul>|
