### ISSUE TITLE
[TSC] CNTT position about Installers Physical/Installer Descriptor Format (xDF).

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#965]
There are different views around about if CNTT is going to specify standard installer format or leave it to OPNFV to decide if this is of a value.

- do need to specify/create one in CNTT?
- do we mind or care if there was one? good to have one? bad to have one? we don't care?

**Comment by rabi-abdel** [comment]
@fuqiao123 I would like to hear your feedback as a leader of the Reference Implementation 1 Workstream

**Comment by fuqiao123** [comment]
> @fuqiao123 I would like to hear your feedback as a leader of the Reference Implementation 1 Workstream

Hi, Rabi. First let me explain why we need a xDF in the whole CNTT scenario. If we want to conduct implementation and verification in Labs, across multi-vendors or open-source communities, and we want to do this automatically, then such xDF is necessary, since currently all the different installer are using different DFs and we have to fill in each and every DF manually. This also answers your question about do we need one? Yes, we need only one. The current fact in the industry is we already have several installers, they each have their own community, all are quite mature, it would be difficult for us to create a "super installer" to cover all the implementation of vendors. Therefore, I think the best we can do is at least we can have a common DF, so that no matter what installer you are using, the end user only need to provide this common DF. This is the single source of truth. 
We had a discussion on the OPNFV Tech-discussion call yesterday about the PDF 2.0. And I think we have already reached consensus within both the CNTT community and OPNFV that we do need such xDFs. 
About the question of whether we should do that in CNTT or OPNFV, I would say both is OK, if we consider OPNFV as the platform for realizing CNTT RI and RC. The current obstacle for promoting this in CNTT is we do not have the audience that can join the discussion for DF. We need the people who really work on the installers, test cases to join the discussion and make sure the DF we design will fit into the requirement. I myself is trying to push this in both CNTT and OPNFV, making sure we can attract the most of the attention between both communities, and the xDF we define can fit into the requirement rather than just a piece of paper...

**Comment by rabi-abdel** [comment]
There are considerable interest of what this description format should be. 
(within OPNFV itself or CNTT to specify it).

**Comment by fuqiao123** [comment]
> There are considerable interest of what this description format should be.
> (within OPNFV itself or CNTT to specify it).

Either is OK for me, and I think currently the center of the discussion is what the DF should be like rather than where it should locate. We now have create DF sample template in chp06 of RI, however that one need further discussion within both community.

**Comment by rabi-abdel** [comment]
> > There are considerable interest of what this description format should be.
> > (within OPNFV itself or CNTT to specify it).
> 
> Either is OK for me, and I think currently the center of the discussion is what the DF should be like rather than where it should locate. We now have create DF sample template in chp06 of RI, however that one need further discussion within both community.

@fuqiao123 makes sense. do you feel we need to approve and merge https://github.com/cntt-n/CNTT/pull/944 now? it has been open for very long.

**Comment by fuqiao123** [comment]
> > > There are considerable interest of what this description format should be.
> > > (within OPNFV itself or CNTT to specify it).
> > 
> > 
> > Either is OK for me, and I think currently the center of the discussion is what the DF should be like rather than where it should locate. We now have create DF sample template in chp06 of RI, however that one need further discussion within both community.
> 
> @fuqiao123 makes sense. do you feel we need to approve and merge #944 now? it has been open for very long.

I think Chen Liang still plan to update the sample when hardware df has been defined. But we can merge #944 now, and create a new PR when the hardware DF requirement is merged.
